### ISSUE TITLE
Two green PRs merged into a red main — nothing re-verifies the combination

### ISSUE THREAD

**Issue by ddteeter** [ddteeter/agentic-guardrails-scaffolding#98]
## What happened

`main` was broken for roughly twenty minutes by two PRs that were each green.

- **#91** added `runStopGate`'s unreadable-working-diff early return, which
  constructs a `GateDecision` literal.
- **#90** added `log` as a **required** field of `GateDecision` (#83's decision
  log).

They touch different lines of `gate.ts`, so there was no textual conflict and
GitHub reported both `MERGEABLE / CLEAN` right up to the merge. Neither PR's CI
run ever saw the other's change. Merging the second produced:

```
src/gate.ts(471,7): error TS2741: Property 'log' is missing in type
'{ outcome: "escalate"; block: true; message: string; nextSession: SessionState;
   nextRecurrence: RecurrenceCounts; }' but required in type 'GateDecision'.
```

Fixed in #97. Two separate agents found the breakage independently within
minutes of each other, which is its own evidence that nothing automated did.

## What is and is not at fault

**Not the repo's gates.** eslint, tsc, the commit gate, the push gate and CI all
work; each ran correctly against the tree it was given. The pre-push gate on #90's
branch passed because, on that branch, the code was correct.

**The merge sequence.** Nothing re-verified the combination. The repo's own
`main` tip carried **no CI run at all** after the merge (`gh run list --commit
<sha>` returned nothing), so the red state was invisible until someone tried to
build.

This is the semantic-conflict case that a textual mergeability check cannot see,
and this repo is unusually exposed to it: a codebase whose whole subject is
"green does not mean good" merged two green branches into a red trunk.

## Suggested fix

1. **Branch protection on `main` with `strict` status checks** — "Require
   branches to be up to date before merging". A stale branch must rebase and
   re-run CI before it can merge, which would have caught this exactly.
   Cheapest option, one setting.
2. **Or a merge queue**, which tests the combination rather than each branch. The
   better answer when several PRs are in flight at once — which was the case here
   (seven open, three contending for `gate.ts`).
3. **Either way, run CI on pushes to `main`.** A red trunk with no run against its
   tip is not detectable by anything but a human building it. The workflow already
   triggers on `push`; confirm `main` is in scope and that a failure is surfaced.

(1) is the minimum. (2) is worth it if this repo keeps landing parallel agent work,
because the failure mode scales with the number of concurrent branches, not with
the size of any one of them.

## Worth noting for the product, not just this repo

guardrails ships a commit rung and a push rung and calls CI authoritative. Neither
rung can see this class: both scope to *a* branch. An adopting repo running the
full guardrail stack would have been just as exposed. Whether that is guardrails'
problem or the forge's is a real question — but the `adopting-guardrails` guidance
currently says nothing about branch protection or merge queues, and the gates it
does install can imply a completeness they do not have.

Found while merging the batch of PRs from the dialed.run audit.

**Comment by ddteeter** [comment]
Concrete detail found while merging this batch: the repo already has a ruleset (`main protection`, id 19153574) — classic branch protection is off, which is why `/branches/main/protection` 404s. Its `required_status_checks` parameters include:

```json
"strict_required_status_checks_policy": false
```

So suggestion (1) in this issue is a **single flag on an existing ruleset**, not new configuration: flipping `strict_required_status_checks_policy` to `true` requires a branch to be up to date with `main` before merging, which is exactly the check that was missing when #90 and #91 combined into a red trunk.

The ruleset also already sets `required_review_thread_resolution: true` and requires `build-test`, so the enforcement point exists and is working — it just does not require the branch to be current.

**Comment by ddteeter** [comment]
**Done — `strict_required_status_checks_policy` is now `true`** on the `main protection` ruleset (id 19153574). Verified by re-reading the ruleset after the change; every other rule is untouched (`deletion`, `non_fast_forward`, the `pull_request` rule with its thread-resolution requirement, and `build-test` as the one required check).

A branch must now be up to date with `main` before it can merge, which is exactly the check that was missing when #90 and #91 — each green on its own — combined into a trunk that did not compile.

What this changes in practice: a PR that goes stale while another merges will need a rebase and a fresh `build-test` run before GitHub will let it in. That is the cost, and it is the point.

**Not closing this issue.** Option (1) is done; the other two suggestions are still live and still worth doing:

- **A merge queue** would test the combination rather than each branch, which scales better than serialized rebases when several PRs are in flight. This batch had seven open at once with three contending for `gate.ts`, so the strict flag will mean real rebase churn the next time that happens.
- **CI on pushes to `main`** — the trunk's tip carried no run at all after the bad merge (`gh run list --commit <sha>` returned nothing), so a red `main` was undetectable by anything except a human building it. Worth confirming `main` is in the workflow's push scope and that a failure is actually surfaced.

The product question raised at the bottom of this issue also stands: neither guardrails rung can see this class, since both scope to a branch, and `adopting-guardrails` says nothing about branch protection or merge queues.
